var app = new Vue({
  el: '#app',
  data: {
    flow:[
      {state: true, title: 'ユーザーを選ぶ'},
      {state: false, title: 'マッチング方法<br>を選ぶ'},
      {state: false, title: '確認する'},
      {state: false, title: '案内を送る'},
    ],
    radioItem01:[
      { value: 'csv1', name: 'Buddy Up!'},
      { value: 'csv2', name: 'CSV'},
    ],
    tagItem01:[
      {id:1, name: "システムエンジニア"},
      {id:2, name: "セールスエンジニア"},
      {id:3, name: "セキュリティエンジニア"},
      {id:4, name: "ネットワークエンジニア"},
      {id:5, name: "アプリケーションエンジニア"},
      {id:6, name: "カスタマーエンジニア"},
      {id:7, name: "サービスエンジニア"},
      {id:8, name: "サポートエンジニア"},
      {id:9, name: "AIエンジニア"},
      {id:10, name: "ブロックチェーンエンジニア"},
      {id:11, name: "プログラマー"},
      {id:12, name: "データベースサーチャー"},
      {id:13, name: "システムコンサルタント"},
      {id:14, name: "システムアナリスト"},
      {id:15, name: "システムアドミニストレータ"},
      {id:16, name: "カスタマーサポート"},
      {id:17, name: "ITコーディネーター"},
      {id:18, name: "OAインストラクター"},
      {id:19, name: "OAオペレーター"},
      {id:20, name: "PCインストラクター"},
      {id:21, name: "ネットワーク管理者"},
      {id:22, name: "インダストリアルデザイナー", cat:2, },
      {id:23, name: "インダストリアルエンジニア", cat:2, },
      {id:24, name: "機械設計士", cat:2, },
      {id:25, name: "ロボット設計技術者", cat:2, },
      {id:26, name: "Webプロデューサー", cat:3, },
      {id:27, name: "Webディレクター", cat:3, },
      {id:28, name: "Webコンテンツプランナー", cat:3, },
      {id:29, name: "Webデザイナー", cat:3, },
      {id:30, name: "Webエンジニア", cat:3, },
      {id:31, name: "コーダー", cat:3, },
      {id:32, name: "Webマーケティング", cat:3, },
      {id:33, name: "Webライター", cat:3, },
      {id:34, name: "ゲームプランナー", cat:4, },
      {id:35, name: "ゲームクリエイター", cat:4, },
      {id:36, name: "ゲームサウンドクリエイター", cat:4, },
      {id:37, name: "ゲームシナリオライター", cat:4, },
      {id:38, name: "ゲームディレクター", cat:4, },
      {id:39, name: "ゲームデザイナー", cat:4, },
      {id:40, name: "ゲームプログラマー", cat:4, },
      {id:41, name: "ゲームプロデューサー", cat:4, },
      {id:42, name: "デジタルフォトグラファー", cat:4, },
      {id:43, name: "画像処理エンジニア", cat:4, },
      {id:44, name: "CGクリエーター", cat:4, },
      {id:45, name: "ＣＧエンジニア", cat:4, },
      {id:46, name: "ゲームグラフィックデザイナー", cat:4, },
      {id:47, name: "漫画原作者", cat:4, },
      {id:48, name: "アニメーター", cat:4, },
      {id:49, name: "デジタル［コンピュータ］アニメーション", cat:4, },
      {id:50, name: "漫画家", cat:4, },
      {id:51, name: "カメラマン", cat:5, },
      {id:52, name: "アートキュレーター", cat:5, },
      {id:53, name: "アートコーディネーター", cat:5, },
      {id:54, name: "ギャラリスト", cat:5, },
      {id:55, name: "学芸員", cat:5, },
      {id:56, name: "アートナビゲーター", cat:5, },
      {id:57, name: "デコレーター", cat:5, },
      {id:58, name: "画家", cat:5, },
      {id:59, name: "フレーマー", cat:5, },
      {id:60, name: "彫金師", cat:5, },
      {id:61, name: "彫刻家", cat:5, },
      {id:62, name: "陶芸家", cat:5, },
      {id:63, name: "版画家", cat:5, },
      {id:64, name: "美術鑑定士", cat:5, },
      {id:65, name: "美術修復家", cat:5, },
      {id:66, name: "書道家", cat:5, },
      {id:67, name: "人形作家", cat:5, },
      {id:68, name: "絵画修復師", cat:5, },
      {id:69, name: "研ぎ師", cat:5, },
      {id:70, name: "写真現像技術者", cat:5, },
      {id:71, name: "彫師", cat:5, },
      {id:72, name: "イラストレーター", cat:6, },
      {id:73, name: "エディトリアルデザイナー", cat:6, },
      {id:74, name: "グラフィックデザイナー", cat:6, },
      {id:75, name: "キャラクターデザイン", cat:6, },
      {id:76, name: "アートディレクター", cat:6, },
      {id:77, name: "絵付師", cat:6, },
      {id:78, name: "刺青師", cat:6, },
      {id:79, name: "筆耕", cat:6, },
      {id:80, name: "プロダクトデザイナー", cat:7, },
      {id:81, name: "パッケージデザイナー", cat:7, },
      {id:82, name: "雑貨デザイナー", cat:7, },
      {id:83, name: "照明デザイナー・照明コンサルタント", cat:7, },
      {id:84, name: "エディター(編集者)", cat:8, },
      {id:85, name: "コピーライター", cat:8, },
      {id:86, name: "ライター", cat:8, },
      {id:87, name: "DTPオペレーター", cat:8, },
      {id:88, name: "DTPディレクター", cat:8, },
      {id:89, name: "DTPデザイナー", cat:8, },
      {id:90, name: "POPライター", cat:8, },
      {id:91, name: "テープリライター", cat:8, },
      {id:92, name: "ジャーナリスト", cat:8, },
      {id:93, name: "新聞記者", cat:8, },
      {id:94, name: "装丁家［ブックデザイナー］", cat:8, },
      {id:95, name: "校正者", cat:8, },
      {id:96, name: "速記者", cat:8, },
      {id:97, name: "ルポライター", cat:8, },
      {id:98, name: "印刷技術者", cat:8, },
      {id:99, name: "雑誌記者", cat:8, },
      {id:100, name: "小説作家", cat:8, },
    ],
    chartList:[
      {
        name: 'FUJITSU TARO',
        tags: ['エンジニア', 'デザイン', 'UI/UX'],
        place: ['渋谷', '品川'],
      },
      {
        name: 'FUJITSU ZIRO',
        tags: ['雑誌記者', 'ジャーナリスト'],
        place: ['渋谷', '浜松町'],
      },
      {
        name: 'FUJITSU TARO',
        tags: ['エンジニア', 'デザイン', 'UI/UX'],
        place: ['渋谷', '品川'],
      },
      {
        name: 'FUJITSU ZIRO',
        tags: ['雑誌記者', 'ジャーナリスト'],
        place: ['渋谷', '浜松町'],
      },
      {
        name: 'FUJITSU TARO',
        tags: ['エンジニア', 'デザイン', 'UI/UX'],
        place: ['渋谷', '品川'],
      },
      {
        name: 'FUJITSU ZIRO',
        tags: ['雑誌記者', 'ジャーナリスト'],
        place: ['渋谷', '浜松町'],
      },
    ]
  },
  methods:{
  },
  computed: {
  }
})
